# Generated by Django 5.1.6 on 2025-03-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_studyplan_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='study_plan',
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
