# Generated by Django 5.1.6 on 2025-03-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_task_study_plan_delete_studyplan_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('study_hours_per_day', models.IntegerField()),
                ('preferred_study_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20)),
                ('break_time', models.IntegerField(help_text='Break time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('deadline', models.DateField()),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='chatbot.studyplan')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField()),
                ('study_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='chatbot.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.subject')),
            ],
        ),
    ]
