# Generated by Django 5.1.6 on 2025-03-17 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_studyplan_subject_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
