# Generated by Django 5.1.6 on 2025-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_studyplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='deadline',
        ),
        migrations.AddField(
            model_name='subject',
            name='days_to_complete',
            field=models.IntegerField(default=7),
        ),
    ]
