# Generated by Django 5.1.6 on 2025-03-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_subject_deadline_subject_days_to_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='study_plan',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='preferred_study_time',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='user',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='deadline_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='preferred_time',
            field=models.CharField(default='08:00 AM', max_length=50),
        ),
        migrations.CreateModel(
            name='StudyPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='chatbot.studyplan')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
